// Generated by scripts/release/create-manifest.ts.
export const releaseEvidence = {
  "tools": {
    "passed": 7,
    "total": 7
  },
  "deterministic_browser": {
    "passed": 17,
    "total": 17
  },
  "csp_production_build": {
    "passed": 17,
    "total": 17
  },
  "local_model": {
    "passed": 125,
    "total": 125
  },
  "chrome_smoke": {
    "passed": 11,
    "total": 11
  },
  "tic_tac_toe": {
    "passed": 1,
    "total": 1
  },
  "visual_routes": {
    "passed": 8,
    "total": 8
  },
  "unit_tests": {
    "passed": 113,
    "total": 113
  },
  "controlled_benchmark": {
    "semantic_passed": 220,
    "total": 220
  },
  "live_benchmark": {
    "semantic_passed": 40,
    "total": 40,
    "rendered_webmcp": 20,
    "pairs": 20,
    "p50_speedup": 6.579570054187292
  }
} as const;
