// Generated by scripts/release/create-manifest.ts.
export const releaseEvidence = {
  "tools": {
    "passed": 7,
    "total": 7
  },
  "deterministic_browser": {
    "passed": 17,
    "total": 17
  },
  "local_model": {
    "passed": 125,
    "total": 125
  },
  "chrome_smoke": {
    "passed": 11,
    "total": 11
  },
  "unit_tests": {
    "passed": 106,
    "total": 106
  },
  "controlled_benchmark": {
    "semantic_passed": 220,
    "total": 220
  }
} as const;
